### ISSUE TITLE
Add ability to ignore the rest of the promise chain and return a value

### ISSUE THREAD

**Issue by samplesizeofone** [then/promise#109]
I'd like to be able to say something like:

```javascript
var result = somePromise.then(function (val) {
   return doSomething(val);
}).catch(function (err) {
   return Promise.return('There was an error');
}).then(function (nextVal) {
    return doSomethingElse(nextVal);
});
```

Where if there is an error, the final then call will forward 'There was an error.' without executing its function.

Other names for Promise.return might be Promise.break, Promise.passthrough, or Promise.bailout.

I think this would address the case where I have several thens but want to handle a possible error after each such that I can bail out if there is a problem.

There are other ways to do this, but the only ones I've found involve repeated code and, more importantly, are error prone. If there's a good way to do this already, I'd be happy to find that out.

Thanks,

Tyler

**Comment by ForbesLindesay** [comment]
You would have to somehow mark the end of the chain, I.e. Where that value should resurface.  The promises themselves have no idea where the boundary of your function is.

An alternative to repetitive code to forward the response is to just have an extra layer of nesting.  People might complain about the pyramid of doom, but in reality that's a total non-issue when it comes to actually debugging your code.  Promises are fundamentally about control flow, not indentation.

The other solution is to enable async/await using babel as a compilation step.  Then you can use try/catch and return just like you would in synchronous code.

Since this is very complex to deal with at a library level, and will be made obsolete by async/await, I'm going to close this issue.

**Comment by samplesizeofone** [comment]
Okay, thanks for the reply. I think I just figured out an acceptable pattern for achieving what I'm aiming for:

https://gist.github.com/samplesizeofone/5a6c9993e816e4dc5c73 if you're interested.

**Comment by ForbesLindesay** [comment]
For what it's worth, it's best practice only to throw/reject with actual error objects.  That way you get a stack trace.  You can always access the plain string as `err.message`.
