### ISSUE TITLE
Jasmine-ajax's respondWith doesn't like asap very much

### ISSUE THREAD

**Issue by madprog** [then/promise#120]
Hi,

I am using [Jasmine-ajax](https://github.com/jasmine/jasmine-ajax) to test a bit of code which uses a `Promise` to make an `XMLHttpRequest`.

I have reproduced the failing problem on a [Plunker](http://plnkr.co/edit/YM9Ld0YCJ5sjaWh3ZQ9O), but from what I have found, the resolution call `ajax_req.respondWith` line 60 will eventually trigger an `asap` call in [`handleResolved`](https://github.com/then/promise/blob/master/src/core.js#L113).

The execution of my callback is delayed, and the test line 64 is executed before it.

Do you know a way to force flushing `asap` queue between lines 63 and 64 in the test code?

**Comment by ForbesLindesay** [comment]
No, promises intentionally force code to be asynchronous, so in general this can't be done.

You may be able to make use of our synchronous extensions (https://github.com/then/promise/blob/master/src/synchronous.js), which are intentionally not documented because they are there purely for advanced optimisation/testing scenarios. These won't help you if you make any calls to `.then` though, since the resulting promise will then not be synchronously resolved.

Most testing frameworks support writing simple asynchronous tests, so I suggest you take that approach.  If you use something like babel you could even use async/await to write tests that look synchronous.

**Comment by madprog** [comment]
Hello @ForbesLindesay and thank you for your quick reply.
Even if I don't fully understand why the resolution and error callbacks have to be asynchronously called too (as they are called from the asynchronous function), I will probably just resign myself to using a `setTimeout`.
Just as sidenotes:
* my example was wrong, as `XMLHttpRequest.DONE` was `undefined` instead of `4`, but the test still fails ;
* jQuery seems to synchronously call the resolution and error callbacks, as my tests passed before I switched to then/promise (I want to get rid of jQuery, as I only used their promises and AJAX functions).

**Comment by ForbesLindesay** [comment]
jQuery is violating the spec by calling those callbacks synchronously.  The problem that means callbacks must be invoked asynchronously is commonly referred to as "unleashing zalgo".  It boils down to wanting to always be able to answer which of the following code snippets is correct:

```js
var after = false;
asyncAction().done(function() {
  assert(after === true);
});
after = true;
```

OR:

```js
var after = false;
asyncAction().done(function() {
  assert(after === false);
});
after = true;
```

Because the callbacks are always fired asynchronously, it's always the first one.

Instead of using `setTimeout`, just chain your callbacks off the promise:

```js
it("should not fail", function(done) {
  var result_data = undefined;

  var req = getStuff().then(function(data) {
    console.log('Not even called!');
    result_data = data;
  });

  expect(jasmine.Ajax.requests.count()).toBe(1);

  var ajax_req = jasmine.Ajax.requests.at(0);
  expect(ajax_req.method).toBe('GET'); // OK
  expect(ajax_req.url).toBe('/stuff'); // OK
  expect(result_data).not.toBeDefined(); // OK

  ajax_req.respondWith({
    status: 200,
    responseText: 'Hello, world!'
  });

  // wait for the promise returned by `.then`, ensuring the callback has fired.
  req.done(function () {
    expect(result_data).toEqual('Hello, world!'); // OK
    done();
  });
});
```

**Comment by madprog** [comment]
Thank you for the precision about the spec. I understand better the functioning of then/promise now.

About chaining a `then`, it is indeed possible in my example, but not in my code, which instantiate a UI component which will handle the promises internally.

I use `respondWith` to fire the change between the loading and the loaded states, and I liked its effects to be synchronous because I didn't have to wait to see its effects on my component.

Maybe I should rethink my architecture, and insert a module which would handle the requests, and that I could mock in my component tests.
