### ISSUE TITLE
Promise.race resolves the combined Promise multiple times, which emits an error/warning event in node

### ISSUE THREAD

**Issue by call-a3** [then/promise#156]
Description says it all.

Since Node 10.12.0 it emits an event when a promise is resolved/rejected multiple times https://nodejs.org/api/process.html#process_event_multipleresolves.

While it's usually overlooked because these errors are by default silently swallowed, this really shouldn't be implemented like this: you're expected to only call one of resolve or reject once.

**Comment by ForbesLindesay** [comment]
Subsequent resolves being ignored is a first class **feature** of promises. It is intended exactly to make it easy to have races like this. Since this isn't using the native promise implementation, we won't fire that event, making multiple resolves for internal cases like this impossible to observe.
